#!/bin/bash

function checkIfValidIP
{
    X=true
    while $X
        do
            IPv4=$(hostname -I)
            oct1=$(echo ${_ip} | tr "." " " | awk '{ print $1 }')

            if [[ -z "$oct1" ]];then
                oct1=127
                echo $IPv4
            fi
            if [[ $oct1 -ne 127  && $oct1 -ne 169 ]];then
                echo $IPv4
                x=false
                break
            fi
        sleep 2
    done
}
checkIfValidIP