#!/bin/bash

COMMONFILE=/usr/local/aloe/scripts/common.sh
. $COMMONFILE

COMP_NAME="$0"
COMP_MESSAGE="Getting local scriptfiles"

function getConfigurationFile
{
	# This file must not be downloaded if it exists, as it userconfigurable and we don't want to wipe that file....
	if [ -e $DEST ];then
		## Only the necessary changes need to be injected here, not possible to replace this file as it is user configurable
		return 0
	fi

	COMPONENT=configuration
	DEST="$CONFIGURATIONFOLDER/$COMPONENT"
    if [ $MQTT_ENABLE == true ];then
		URLEND="prov/get/update/component?Component=$COMPONENT&Type=$DEVTYPE&Version=1"
		SRC="$HOSTURL$URLEND"

		curling ${SRC} ${TMPFILE}
		if [ $? -eq 0 ];then
			mv ${TMPFILE} ${DEST}
		else
			FUNC_NAME="${FUNCNAME[0]}"
			FUNC_SUCCESS=false
			FUNC_MESSAGE="Will not continue due to error in downloaded file - ${COMPONENT}"
			functionInfo
			return 1
		fi
	else
		cp $STORAGEFOLDER/conf/$COMPONENT $DEST
	fi
}

function getCommonFile
{
	COMPONENT=common.sh
	DEST="$SCRIPTFOLDER/$COMPONENT"
    if [ $MQTT_ENABLE == true ];then
		URLEND="prov/get/update/component?Component=$COMPONENT&Type=$DEVTYPE&Version=1"
		SRC="$HOSTURL$URLEND"

		curling ${SRC} ${TMPFILE}
		if [ $? -eq 0 ];then
			mv ${TMPFILE} ${DEST}
		else
			FUNC_NAME="${FUNCNAME[0]}"
			FUNC_SUCCESS=false
			FUNC_MESSAGE="Will not continue due to error in downloaded file - ${COMPONENT}"
			functionInfo
			return 1
		fi
	else
		cp $STORAGEFOLDER/scripts/$COMPONENT $DEST
	fi
}

function getDpkgHelpScript
{
	COMPONENT=dpkg-helpscript.sh
	DEST="$SCRIPTFOLDER/$COMPONENT"
	if [ $MQTT_ENABLE == true ];then
		URLEND="prov/get/update/component?Component=$COMPONENT&Type=$DEVTYPE&Version=1"
		SRC="$HOSTURL$URLEND"

		curling ${SRC} ${TMPFILE}
		if [ $? -eq 0 ];then
			mv ${TMPFILE} ${DEST}
		else
			FUNC_NAME="${FUNCNAME[0]}"
			FUNC_SUCCESS=false
			FUNC_MESSAGE="Will not continue due to error in downloaded file - ${COMPONENT}"
			functionInfo
			return 1
		fi
	else
		cp $STORAGEFOLDER/scripts/$COMPONENT $DEST
	fi
}

function getCheckIpScript
{
	COMPONENT=checkip
	DEST="$SCRIPTFOLDER/checkIP.sh"
	if [ $MQTT_ENABLE == true ];then
		URLEND="prov/get/update/component?Component=$COMPONENT&Type=$DEVTYPE&Version=1"
		SRC="$HOSTURL$URLEND"

		curling ${SRC} ${TMPFILE}
		if [ $? -eq 0 ];then
			mv ${TMPFILE} ${DEST}
		else
			FUNC_NAME="${FUNCNAME[0]}"
			FUNC_SUCCESS=false
			FUNC_MESSAGE="Will not continue due to error in downloaded file - ${COMPONENT}"
			functionInfo
			return 1
		fi
	else
		cp $STORAGEFOLDER/scripts/$COMPONENT $DEST
	fi
}

function getOphrysDisplayConfigScript
{
    COMPONENT=setdisplayconfig.sh
    DEST=$SCRIPTFOLDER/$COMPONENT
    if [ $MQTT_ENABLE == true ];then
		URLEND="prov/get/update/component?Component=$COMPONENT&Type=$DEVTYPE&Version=1"
		SRC="$HOSTURL$URLEND"

		curling ${SRC} ${TMPFILE}
		if [ $? -eq 0 ];then
			mv ${TMPFILE} ${DEST}
		else
			FUNC_NAME="${FUNCNAME[0]}"
			FUNC_SUCCESS=false
			FUNC_MESSAGE="Will not continue due to error in downloaded file - ${COMPONENT}"
			functionInfo
			return 1
		fi
	else
		cp $STORAGEFOLDER/scripts/$COMPONENT $DEST
	fi
}

function getWebclientScript
{
	COMPONENT=displaywebpagescript.sh
	DEST="$SCRIPTFOLDER/$COMPONENT"
    if [ $MQTT_ENABLE == true ];then
		URLEND="prov/get/update/component?Component=$COMPONENT&Type=$DEVTYPE&Version=1"
		SRC="$HOSTURL$URLEND"

		curling ${SRC} ${TMPFILE}
		if [ $? -eq 0 ];then
			mv ${TMPFILE} ${DEST}
		else
			FUNC_NAME="${FUNCNAME[0]}"
			FUNC_SUCCESS=false
			FUNC_MESSAGE="Will not continue due to error in downloaded file - ${COMPONENT}"
			functionInfo
			return 1
		fi
	else
		cp $STORAGEFOLDER/scripts/$COMPONENT $DEST
	fi
}

componentInfo
getConfigurationFile || COMP_SUCCESS=false
getCommonFile || COMP_SUCCESS=false
getDpkgHelpScript || COMP_SUCCESS=false
getCheckIpScript || COMP_SUCCESS=false
getOphrysDisplayConfigScript || COMP_SUCCESS=false
getWebclientScript || COMP_SUCCESS=false
reportResult