#!/bin/bash

COMMONFILE=/usr/local/aloe/scripts/common.sh
. $COMMONFILE

COMP_NAME="$0"
COMP_MESSAGE=""

function xserverInstall
{
    FUNC_NAME="${FUNCNAME[0]}"

    if !(apt-get -y install --no-install-recommends xserver-xorg &>> $INSTALL_LOG);then

        safeApt $FUNC_NAME

        if !(apt-get -y install --no-install-recommends xserver-xorg &>> $INSTALL_LOG);then
            FUNC_MESSAGE="$FUNC_NAME - Unreparable error - failed"
            functionInfo
            return 1
        fi
    fi
}

function openboxInstall
{
    FUNC_NAME="${FUNCNAME[0]}"

    if !(apt-get -y install openbox &>> $INSTALL_LOG);then

        safeApt $FUNC_NAME

        if !(apt-get -y install openbox &>> $INSTALL_LOG);then
            FUNC_MESSAGE="$FUNC_NAME - Unreparable error - failed"
            functionInfo
            return 1
        fi
    fi
}

function lightdmInstall
{
    FUNC_NAME="${FUNCNAME[0]}"

    if !(apt-get -y install lightdm &>> $INSTALL_LOG);then

        safeApt $FUNC_NAME

        if !(apt-get -y install lightdm &>> $INSTALL_LOG);then
            FUNC_MESSAGE="$FUNC_NAME - Unreparable error - failed"
            functionInfo
            return 1
        fi
    fi
}

updateApt
COMP_MESSAGE="Installing Xserver"
componentInfo
xserverInstall || COMP_SUCCESS=false
#################
COMP_MESSAGE="Installing Openbox"
componentInfo
openboxInstall || COMP_SUCCESS=false
#################
COMP_MESSAGE="Installing LightDM"
componentInfo
if [ ! -f $NEWINSTALL ];then
lightdmInstall || COMP_SUCCESS=false
fi
reportResult