#!/bin/bash

COMMONFILE=/usr/local/aloe/scripts/common.sh
. $COMMONFILE

COMP_NAME="wearedone-finalize-install-script"
COMP_MESSAGE="Install finished - device will now reboot"

MSG=$COMP_MESSAGE
INSTALLPROGRESS=100

INSTALLSERVICE="/etc/systemd/system/aloe_getstarthere.service"
INSTALLFILES_DEST="/home/pi/used_install_files"

function cleanUp
{
	if [ $MQTT_ENABLE == true ];then

		if [ ! -e $INSTALLFILES_DEST ];then
			mkdir -p /home/pi/used_install_files
		fi

		if [ -e $STARTINSTALLFILE ];then
			cp $STARTINSTALLFILE /home/pi/used_install_files/
			rm -r /home/pi/aloe_preinstall
		fi

		if [ -e $INSTALLSERVICE ];then
			rm $INSTALLSERVICE
			systemctl daemon-reload
		fi

		if [ -e $INSTALLSERVICE ];then
			rm /etc/systemd/system/aloe_getstarthere.service
			systemctl daemon-reload
		fi

		if [ -f $NEWINSTALL ];then
			rm $NEWINSTALL
		fi
	fi
}

function calculateTimeForInstall
{
	TIMINGFILE="/tmp/timing"

	echo "" >> $INSTALL_LOG
	echo "#####################" >> $INSTALL_LOG
	echo "FULL INSTALL FINISHED: $(date)" >> $INSTALL_LOG
	echo "" >> $INSTALL_LOG

	if [ -f $TIMINGFILE ];then
		. $TIMINGFILE
		END=$(date +"%H:%M:%S")

		# Convert the times to seconds from the Epoch
		SEC1=`date +%s -d ${START}`
		SEC2=`date +%s -d ${END}`

		# Use expr to do the math, let's say TIME1 was the start and TIME2 was the finish
		DIFFSEC=`expr ${SEC2} - ${SEC1}`

		# And use date to convert the seconds back to something more meaningful
		echo "TOTAL INSTALL TIME:" `date +%M:%S -ud @${DIFFSEC}` "(min:ss)"|& tee -a $INSTALL_LOG
		echo "#####################" >> $INSTALL_LOG

		# remove the temporary file used for timing the install
		if [ -f $TIMINGFILE ];then
			rm $TIMINGFILE
		fi
	else
		echo "NOTICE from $COMP_NAME: " |& tee -a $INSTALL_LOG
		echo "Not possible to calculate install time as no inital time was found - missing file: $TIMINGFILE" |& tee -a $INSTALL_LOG
		echo "#####################" >> "$INSTALL_LOG"
	fi
}

cleanUp || COMP_SUCCESS=false
reportResult
# "calculateTimeForInstall" needs to be run after "reportResult" in order to append to the very end of the log file
calculateTimeForInstall